// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"url-shortener/interal/controller"
	"url-shortener/interal/service"
)

// Injectors from wire.go:

func InitializeUrlController() controller.UrlController {
	urlService := service.NewUrlService()
	urlController := controller.NewUrlController(urlService)
	return urlController
}
